Add Torchx README and update Makefile to run on macOS builtin make

diff --git a/torchx/Makefile b/torchx/Makefile
--- a/torchx/Makefile
+++ b/torchx/Makefile
@@ -1,8 +1,3 @@
-ifndef LIBTORCH_DIR
-	$(error LIBTORCH_DIR env var is not set. It should point to the directory, where libtorch is installed. \
-		You can download libtorch here: https://pytorch.org/get-started/locally/)
-endif
-
 LIBTORCH_VERSION := $(shell head -c 3 $(LIBTORCH_DIR)/build-version)
 REQUIRED_LIBTORCH_VERSION := 1.8
 
@@ -26,15 +21,19 @@ endif
 build: check_version $(MIX_APP_PATH)/priv/torchx.so
 
 check_version:
-ifneq "$(LIBTORCH_VERSION)" "$(REQUIRED_LIBTORCH_VERSION)"
-	$(error libtorch version should be at least $(REQUIRED_LIBTORCH_VERSION). Got: $(LIBTORCH_VERSION) \
-	  Use latest nightly build, if neccessary. You can download it here: https://pytorch.org/get-started/locally/)
-endif
-	@echo > /dev/null
+	@ if [ -z "$(LIBTORCH_DIR)" ]; then \
+		echo "LIBTORCH_DIR env var is not set. It should point to the directory, where LibTorch is installed."; \
+		echo "You can download LibTorch here: https://pytorch.org/get-started/locally/"; \
+		exit 1; \
+	fi
 
+	@ if [ $(LIBTORCH_VERSION) != $(REQUIRED_LIBTORCH_VERSION) ]; then \
+		echo "LibTorch version should be at least $(REQUIRED_LIBTORCH_VERSION). Got: $(LIBTORCH_VERSION)."; \
+		echo "You can download LibTorch here: https://pytorch.org/get-started/locally/"; \
+		exit 1; \
+	fi
 
 $(MIX_APP_PATH)/priv/torchx.so: c_src/torchx.cpp
 	@echo 'Compiling: '$<
 	@mkdir -p $(MIX_APP_PATH)/priv
 	@$(CXX) $(CFLAGS) c_src/torchx.cpp -o $(MIX_APP_PATH)/priv/torchx.so $(LDFLAGS)
-
